services:
  - type: web
    name: api-gateway
    runtime: node
    repo: https://github.com/edoardok-cmd/BoomCard
    rootDir: api-gateway
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://boomcard-dashboard.netlify.app