apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-service
  labels:
    app: qr-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qr-service
  template:
    metadata:
      labels:
        app: qr-service
    spec:
      containers:
      - name: qr-service
        image: ghcr.io/yourusername/qr-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qr-service-service
spec:
  selector:
    app: qr-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP